# Generated by Django 3.0.10 on 2020-12-22 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0002_auto_20201221_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fu', to=settings.AUTH_USER_MODEL)),
                ('self_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='su', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
