# Generated by Django 3.0.10 on 2020-12-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=280),
        ),
    ]
